const mongoose=require("mongoose");

const schema=new mongoose.Schema({
    title:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    bedrooms:{
        type:Number,
        required:true
    },
    bathrooms:{
        type:Number,
        required:true
    },
    area:{
        type:Number,
        required:true
    },
    address:{
        type:String,
        require:true
    },
    city:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    country:{
        type:String
    },
    images:{
        type:[String],
        required:true
    },
    userId:{
        type:mongoose.SchemaTypes.ObjectId,
        ref:"User",
        required:true
    },
    areaunit:{
        type:mongoose.SchemaTypes.ObjectId,
        ref:"AreaUnit",
        required:true
    },
    list:{
        type:mongoose.SchemaTypes.ObjectId,
        ref:"ListingType",
        required:true
    },
    status:{
        type:mongoose.SchemaTypes.ObjectId,
        ref:"Status",
        required:true
    },
    proptype:{
        type:mongoose.SchemaTypes.ObjectId,
        ref:"PropertyType",
        required:true
    },
    currency:{
        type:mongoose.SchemaTypes.ObjectId,
        ref:"Currency",
        required:true
    }
},{    timestamps: true
});

module.exports=mongoose.model("Posts",schema);